"""Strip_Tray CAVITY insert (steel size, ABS shrink 0.5 % applied). Generated by hemosure_mold.py."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import hemosure_mold as HM


def gen_step():
    core, cavity, _ = HM.build("Strip_Tray", check=False)
    return core if "CAVITY" == "CORE" else cavity
