"""Optical_Block CORE insert (steel size, ABS shrink 0.5 % applied). Generated by hemosure_mold.py."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import hemosure_mold as HM


def gen_step():
    core, cavity, _ = HM.build("Optical_Block", check=False)
    return core if "CORE" == "CORE" else cavity
